# Generated by Django 4.0.2 on 2022-02-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Picmodel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="")),
                ("name", models.CharField(max_length=256, null=True)),
                ("artist", models.CharField(max_length=256, null=True)),
                ("desc", models.TextField(null=True)),
                ("nation", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "pictures",
            },
        ),
    ]
